name: "Deploy Hublss app"

on:
  pull_request:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Build App
        run: ./gradlew assembleAsiaDebug